// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		double countBigger = 0.0;
		double counyLessOrEqual = 0.0;
		for (int i=0; i<N; i++)
		{
			double A = Math.random();
			if(A>0.5) countBigger++;
			else counyLessOrEqual++;
		}
		if (countBigger != 0 && counyLessOrEqual != 0) {
			double ratio = countBigger/counyLessOrEqual;
			System.out.println("> 0.5: "+(int)(countBigger));
			System.out.println("<= 0.5: "+(int)(counyLessOrEqual));
			System.out.println("ratio: "+ratio);
		}
		else
		{
			System.out.println("> 0.5: "+countBigger);
		    System.out.println("<= 0.5: "+counyLessOrEqual);

		}	    
	}
}
